### This is a template, can not be used as a root pipeline
###
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
parameters:
  environment: ''

stages:

- stage: IaC${{ parameters.environment }}
  displayName: '${{ parameters.environment }} updating Infrastructure' 
  condition: or(eq('${{ parameters.environment }}', 'Stage'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables:
  # This group must include following variables: 
  # - ServicePrincipalID (Client/App ID)
  # - ServicePrincipalSecret (Client Secret)
  # - TenantId (AAD Id)
  # - SubscriptionId (Azure Subscription)
  - group: SubscriptionDetails
  # This group must include following variables: 
  # - TFStateRG (Resource Group for Terraform state)
  # - TFStateStA (Terraform state store storage account)
  # - TFStateLoc (Terraform state store storage account and resource group location)
  - group: StateStore${{ parameters.environment }}
  # This group must include following variables: 
  # - BotName (Name of the Bot)
  # - Domain (Custom Domain name for the Bot)
  # - BotRegions (Azure Regions for the Bot PowerShell Array format)
  # - BotGlobalLocation (Azure Regions for global resources)
  # - PFXImportPassword (PFX file import password for SSL Bot Certificate)
  - group: BotConfig${{ parameters.environment }}

  jobs:
  - deployment: IaC
    displayName: 'Updating Infrastructure ${{ parameters.environment }}'
    
    pool:
      name: Default
      demands:
      - docker
    container: geobotagent

    environment: ${{ parameters.environment }}
    strategy: 
      runOnce:
        deploy:
          steps:
          - template: jobs/steps/iac.yaml  # Template reference
            parameters:
              sslfilename: '${{ parameters.sslfilename }}'