// <auto-generated>
// Code generated by LUISGen .\AddressFinder.json -cs Luis.AddressFinder -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace GeoBot.CognitiveModels
{
    public partial class AddressFinder: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            None, 
            POI_GetAddress, 
            Utilities_Cancel, 
            Utilities_Confirm, 
            Utilities_Escalate, 
            Utilities_FinishTask, 
            Utilities_GoBack, 
            Utilities_Help, 
            Utilities_ReadAloud, 
            Utilities_Reject, 
            Utilities_Repeat, 
            Utilities_SelectAny, 
            Utilities_SelectItem, 
            Utilities_SelectNone, 
            Utilities_ShowNext, 
            Utilities_ShowPrevious, 
            Utilities_StartOver, 
            Utilities_Stop
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Utilities_DirectionalReference;

            // Built-in entities
            public GeographyV2[] geographyV2;

            public double[] number;

            public double[] ordinal;

            // Instance
            public class _Instance
            {
                public InstanceData[] Utilities_DirectionalReference;
                public InstanceData[] geographyV2;
                public InstanceData[] number;
                public InstanceData[] ordinal;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<AddressFinder>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
